"""
forex/universe.py
-----------------
Instrument definitions for the FX trend-following strategy.

All pairs use AssetType=FxSpot — confirmed available in Saxo SIM.
UICs are hard-coded from the Saxo SIM reference data (permanent for spot FX,
no expiry / roll required).

Run `python forex/runner.py --info` to verify UICs are live.
"""

# ── FX pair definitions ──────────────────────────────────────────────────────
# All confirmed FxSpot UICs from Saxo SIM /ref/v1/instruments endpoint.
# Bars arrive as CloseAsk/CloseBid (same format as XAUUSD in futures module).
# Amount in orders = units of base currency (e.g. EUR for EURUSD).

PAIRS = [
    # ── G7 Majors ────────────────────────────────────────────────────────────
    {
        "symbol":      "EURUSD",
        "description": "Euro / US Dollar",
        "base":        "EUR",
        "quote":       "USD",
        "uic":         21,
        "yf_ticker":   "EURUSD=X",
        "pip_size":    0.0001,   # 1 pip = 0.0001
        "min_units":   1_000,    # Saxo minimum trade size
    },
    {
        "symbol":      "GBPUSD",
        "description": "British Pound / US Dollar",
        "base":        "GBP",
        "quote":       "USD",
        "uic":         31,
        "yf_ticker":   "GBPUSD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDJPY",
        "description": "US Dollar / Japanese Yen",
        "base":        "USD",
        "quote":       "JPY",
        "uic":         42,
        "yf_ticker":   "USDJPY=X",
        "pip_size":    0.01,    # JPY pairs: 1 pip = 0.01
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDUSD",
        "description": "Australian Dollar / US Dollar",
        "base":        "AUD",
        "quote":       "USD",
        "uic":         4,
        "yf_ticker":   "AUDUSD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDCAD",
        "description": "US Dollar / Canadian Dollar",
        "base":        "USD",
        "quote":       "CAD",
        "uic":         38,
        "yf_ticker":   "USDCAD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDUSD",
        "description": "New Zealand Dollar / US Dollar",
        "base":        "NZD",
        "quote":       "USD",
        "uic":         37,
        "yf_ticker":   "NZDUSD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDCHF",
        "description": "US Dollar / Swiss Franc",
        "base":        "USD",
        "quote":       "CHF",
        "uic":         39,
        "yf_ticker":   "USDCHF=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── Cross Pairs: Tier 1 (confirmed Saxo SIM 2026-08-17) ─────────────────
    {
        "symbol":      "EURGBP",
        "description": "Euro / British Pound",
        "base":        "EUR",
        "quote":       "GBP",
        "uic":         17,
        "yf_ticker":   "EURGBP=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURJPY",
        "description": "Euro / Japanese Yen",
        "base":        "EUR",
        "quote":       "JPY",
        "uic":         18,
        "yf_ticker":   "EURJPY=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPJPY",
        "description": "British Pound / Japanese Yen",
        "base":        "GBP",
        "quote":       "JPY",
        "uic":         26,
        "yf_ticker":   "GBPJPY=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDJPY",
        "description": "Australian Dollar / Japanese Yen",
        "base":        "AUD",
        "quote":       "JPY",
        "uic":         2,
        "yf_ticker":   "AUDJPY=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADJPY",
        "description": "Canadian Dollar / Japanese Yen",
        "base":        "CAD",
        "quote":       "JPY",
        "uic":         6,
        "yf_ticker":   "CADJPY=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    # ── Cross Pairs: Tier 2 — EUR crosses ────────────────────────────────────
    {
        "symbol":      "EURAUD",
        "description": "Euro / Australian Dollar",
        "base":        "EUR",
        "quote":       "AUD",
        "uic":         12,
        "yf_ticker":   "EURAUD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURNZD",
        "description": "Euro / New Zealand Dollar",
        "base":        "EUR",
        "quote":       "NZD",
        "uic":         2072,
        "yf_ticker":   "EURNZD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURCAD",
        "description": "Euro / Canadian Dollar",
        "base":        "EUR",
        "quote":       "CAD",
        "uic":         13,
        "yf_ticker":   "EURCAD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURCHF",
        "description": "Euro / Swiss Franc",
        "base":        "EUR",
        "quote":       "CHF",
        "uic":         14,
        "yf_ticker":   "EURCHF=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── Cross Pairs: Tier 2 — GBP crosses ────────────────────────────────────
    {
        "symbol":      "GBPAUD",
        "description": "British Pound / Australian Dollar",
        "base":        "GBP",
        "quote":       "AUD",
        "uic":         22,
        "yf_ticker":   "GBPAUD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPCAD",
        "description": "British Pound / Canadian Dollar",
        "base":        "GBP",
        "quote":       "CAD",
        "uic":         23,
        "yf_ticker":   "GBPCAD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPCHF",
        "description": "British Pound / Swiss Franc",
        "base":        "GBP",
        "quote":       "CHF",
        "uic":         24,
        "yf_ticker":   "GBPCHF=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPNZD",
        "description": "British Pound / New Zealand Dollar",
        "base":        "GBP",
        "quote":       "NZD",
        "uic":         28,
        "yf_ticker":   "GBPNZD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── Cross Pairs: Tier 2 — AUD / NZD crosses ──────────────────────────────
    {
        "symbol":      "AUDCAD",
        "description": "Australian Dollar / Canadian Dollar",
        "base":        "AUD",
        "quote":       "CAD",
        "uic":         1,
        "yf_ticker":   "AUDCAD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDCHF",
        "description": "Australian Dollar / Swiss Franc",
        "base":        "AUD",
        "quote":       "CHF",
        "uic":         5027,
        "yf_ticker":   "AUDCHF=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDNZD",
        "description": "Australian Dollar / New Zealand Dollar",
        "base":        "AUD",
        "quote":       "NZD",
        "uic":         3,
        "yf_ticker":   "AUDNZD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDJPY",
        "description": "New Zealand Dollar / Japanese Yen",
        "base":        "NZD",
        "quote":       "JPY",
        "uic":         36,
        "yf_ticker":   "NZDJPY=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDCAD",
        "description": "New Zealand Dollar / Canadian Dollar",
        "base":        "NZD",
        "quote":       "CAD",
        "uic":         33,
        "yf_ticker":   "NZDCAD=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDCHF",
        "description": "New Zealand Dollar / Swiss Franc",
        "base":        "NZD",
        "quote":       "CHF",
        "uic":         34,
        "yf_ticker":   "NZDCHF=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── Cross Pairs: Tier 2 — CHF / JPY ──────────────────────────────────────
    {
        "symbol":      "CHFJPY",
        "description": "Swiss Franc / Japanese Yen",
        "base":        "CHF",
        "quote":       "JPY",
        "uic":         8,
        "yf_ticker":   "CHFJPY=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    # ── Cross Pairs: Tier 2 — CAD crosses ────────────────────────────────────
    {
        "symbol":      "CADCHF",
        "description": "Canadian Dollar / Swiss Franc",
        "base":        "CAD",
        "quote":       "CHF",
        "uic":         7,            # sequential gap between CADJPY=6 and CHFJPY=8
        "yf_ticker":   "CADCHF=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── Scandinavian pairs (oil-linked, frequent weekend gaps) ────────────────
    # UICs 19, 20, 40, 41 inferred from sequential Saxo numbering — verify with:
    #   python forex/runner.py --info
    {
        "symbol":      "EURNOK",
        "description": "Euro / Norwegian Krone",
        "base":        "EUR",
        "quote":       "NOK",
        "uic":         19,
        "yf_ticker":   "EURNOK=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURSEK",
        "description": "Euro / Swedish Krona",
        "base":        "EUR",
        "quote":       "SEK",
        "uic":         20,
        "yf_ticker":   "EURSEK=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDNOK",
        "description": "US Dollar / Norwegian Krone",
        "base":        "USD",
        "quote":       "NOK",
        "uic":         43,           # was 40 (guessed, never verified) — that's actually
                                      # USDCZK; corrected 2026-08-21 via live /ref/v1/instruments lookup
        "yf_ticker":   "USDNOK=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDSEK",
        "description": "US Dollar / Swedish Krona",
        "base":        "USD",
        "quote":       "SEK",
        "uic":         44,           # was 41 (guessed, never verified) — corrected 2026-08-21
        "yf_ticker":   "USDSEK=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── EM / USD pairs (volatile, large weekend gaps) ─────────────────────────
    {
        "symbol":      "USDDKK",
        "description": "US Dollar / Danish Krone",
        "base":        "USD",
        "quote":       "DKK",
        "uic":         41,           # was 43 (guessed, never verified) — corrected 2026-08-21
        "yf_ticker":   "USDDKK=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDMXN",
        "description": "US Dollar / Mexican Peso",
        "base":        "USD",
        "quote":       "MXN",
        "uic":         1348,         # was 44 (guessed, never verified — wildly wrong).
                                      # Corrected 2026-08-21 via live /ref/v1/instruments lookup.
        "yf_ticker":   "USDMXN=X",
        "pip_size":    0.0001,
        "min_units":   1_000,
    },
    # ── EM / exotic crosses (added 2026-08-21 for SIM-only broad testing ──────
    # Wider spreads / lower liquidity than the 34 majors above — kept OUT of
    # LBO specifically (see strategy_london_breakout.py) but available to every
    # other strategy for SIM testing. pip_size derived from Saxo's own instrument
    # Format.Decimals (pip_size = 10 ** -(decimals - 1)), min_units = Saxo's own
    # MinimumTradeSize — both pulled live via /ref/v1/instruments/details, not guessed.
    {
        "symbol":      "AUDCNH",
        "description": "Australian Dollar / Offshore Chinese Renminbi",
        "base":        "AUD",
        "quote":       "CNH",
        "uic":         52823,
        "yf_ticker":   "AUDCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDCZK",
        "description": "Australian Dollar / Czech Koruna",
        "base":        "AUD",
        "quote":       "CZK",
        "uic":         9433,
        "yf_ticker":   "AUDCZK=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDHKD",
        "description": "Australian Dollar / Hong Kong Dollar",
        "base":        "AUD",
        "quote":       "HKD",
        "uic":         5394,
        "yf_ticker":   "AUDHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDHUF",
        "description": "Australian Dollar / Hungarian Forint",
        "base":        "AUD",
        "quote":       "HUF",
        "uic":         9434,
        "yf_ticker":   "AUDHUF=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDMXN",
        "description": "Australian Dollar / Mexican Peso",
        "base":        "AUD",
        "quote":       "MXN",
        "uic":         30651,
        "yf_ticker":   "AUDMXN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDPLN",
        "description": "Australian Dollar / Polish Zloty",
        "base":        "AUD",
        "quote":       "PLN",
        "uic":         9435,
        "yf_ticker":   "AUDPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDSGD",
        "description": "Australian Dollar / Singapore Dollar",
        "base":        "AUD",
        "quote":       "SGD",
        "uic":         9436,
        "yf_ticker":   "AUDSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDTRY",
        "description": "Australian Dollar / Turkish Lira",
        "base":        "AUD",
        "quote":       "TRY",
        "uic":         23509,
        "yf_ticker":   "AUDTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "AUDZAR",
        "description": "Australian Dollar / South African Rand",
        "base":        "AUD",
        "quote":       "ZAR",
        "uic":         23610,
        "yf_ticker":   "AUDZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADCNH",
        "description": "Canadian Dollar / Offshore Chinese Renminbi",
        "base":        "CAD",
        "quote":       "CNH",
        "uic":         52824,
        "yf_ticker":   "CADCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADHKD",
        "description": "Canadian Dollar / Hong Kong Dollar",
        "base":        "CAD",
        "quote":       "HKD",
        "uic":         994174,
        "yf_ticker":   "CADHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADMXN",
        "description": "Canadian Dollar / Mexican Peso",
        "base":        "CAD",
        "quote":       "MXN",
        "uic":         23739,
        "yf_ticker":   "CADMXN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADPLN",
        "description": "Canadian Dollar / Polish Zloty",
        "base":        "CAD",
        "quote":       "PLN",
        "uic":         23690,
        "yf_ticker":   "CADPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADSGD",
        "description": "Canadian Dollar / Singapore Dollar",
        "base":        "CAD",
        "quote":       "SGD",
        "uic":         682710,
        "yf_ticker":   "CADSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADTRY",
        "description": "Canadian Dollar / Turkish Lira",
        "base":        "CAD",
        "quote":       "TRY",
        "uic":         23519,
        "yf_ticker":   "CADTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CADZAR",
        "description": "Canadian Dollar / South African Rand",
        "base":        "CAD",
        "quote":       "ZAR",
        "uic":         2906229,
        "yf_ticker":   "CADZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFCNH",
        "description": "Swiss Franc / Offshore Chinese Renminbi",
        "base":        "CHF",
        "quote":       "CNH",
        "uic":         52828,
        "yf_ticker":   "CHFCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFCZK",
        "description": "Swiss Franc / Czech Koruna",
        "base":        "CHF",
        "quote":       "CZK",
        "uic":         9438,
        "yf_ticker":   "CHFCZK=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFHKD",
        "description": "Swiss Franc / Hong Kong Dollar",
        "base":        "CHF",
        "quote":       "HKD",
        "uic":         39771,
        "yf_ticker":   "CHFHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFHUF",
        "description": "Swiss Franc / Hungarian Forint",
        "base":        "CHF",
        "quote":       "HUF",
        "uic":         9439,
        "yf_ticker":   "CHFHUF=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFMXN",
        "description": "Swiss Franc / Mexican Peso",
        "base":        "CHF",
        "quote":       "MXN",
        "uic":         30631,
        "yf_ticker":   "CHFMXN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFPLN",
        "description": "Swiss Franc / Polish Zloty",
        "base":        "CHF",
        "quote":       "PLN",
        "uic":         6561,
        "yf_ticker":   "CHFPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFSGD",
        "description": "Swiss Franc / Singapore Dollar",
        "base":        "CHF",
        "quote":       "SGD",
        "uic":         23521,
        "yf_ticker":   "CHFSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFTRY",
        "description": "Swiss Franc / Turkish Lira",
        "base":        "CHF",
        "quote":       "TRY",
        "uic":         23520,
        "yf_ticker":   "CHFTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CHFZAR",
        "description": "Swiss Franc / South African Rand",
        "base":        "CHF",
        "quote":       "ZAR",
        "uic":         9440,
        "yf_ticker":   "CHFZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "CNHHKD",
        "description": "Offshore Chinese Renminbi / Hong Kong Dollar",
        "base":        "CNH",
        "quote":       "HKD",
        "uic":         300875,
        "yf_ticker":   "CNHHKD=X",
        "pip_size":    0.001,
        "min_units":   6_000,
    },
    {
        "symbol":      "CNHJPY",
        "description": "Offshore Chinese Renminbi / Japanese Yen",
        "base":        "CNH",
        "quote":       "JPY",
        "uic":         52873,
        "yf_ticker":   "CNHJPY=X",
        "pip_size":    0.001,
        "min_units":   6_000,
    },
    {
        "symbol":      "CZKPLN",
        "description": "Czech Koruna / Polish Zloty",
        "base":        "CZK",
        "quote":       "PLN",
        "uic":         36629,
        "yf_ticker":   "CZKPLN=X",
        "pip_size":    0.0001,
        "min_units":   10_000,
    },
    {
        "symbol":      "EURCNH",
        "description": "Euro / Offshore Chinese Renminbi",
        "base":        "EUR",
        "quote":       "CNH",
        "uic":         52830,
        "yf_ticker":   "EURCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURCZK",
        "description": "Euro / Czech Koruna",
        "base":        "EUR",
        "quote":       "CZK",
        "uic":         15,
        "yf_ticker":   "EURCZK=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURHKD",
        "description": "Euro / Hong Kong Dollar",
        "base":        "EUR",
        "quote":       "HKD",
        "uic":         5400,
        "yf_ticker":   "EURHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURHUF",
        "description": "Euro / Hungarian Forint",
        "base":        "EUR",
        "quote":       "HUF",
        "uic":         2071,
        "yf_ticker":   "EURHUF=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURILS",
        "description": "Euro / Israeli Shekel",
        "base":        "EUR",
        "quote":       "ILS",
        "uic":         39057,
        "yf_ticker":   "EURILS=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURMXN",
        "description": "Euro / Mexican Pesos",
        "base":        "EUR",
        "quote":       "MXN",
        "uic":         2871,
        "yf_ticker":   "EURMXN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURPLN",
        "description": "Euro / Polish Zloty",
        "base":        "EUR",
        "quote":       "PLN",
        "uic":         1343,
        "yf_ticker":   "EURPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURRON",
        "description": "Euro / Romanian Leu",
        "base":        "EUR",
        "quote":       "RON",
        "uic":         24443,
        "yf_ticker":   "EURRON=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURSGD",
        "description": "Euro / Singapore Dollar",
        "base":        "EUR",
        "quote":       "SGD",
        "uic":         4800,
        "yf_ticker":   "EURSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURTHB",
        "description": "Euro / Thai Baht",
        "base":        "EUR",
        "quote":       "THB",
        "uic":         9446,
        "yf_ticker":   "EURTHB=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURTRY",
        "description": "Euro / Turkish Lira",
        "base":        "EUR",
        "quote":       "TRY",
        "uic":         13927,
        "yf_ticker":   "EURTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "EURZAR",
        "description": "Euro / South African Rand",
        "base":        "EUR",
        "quote":       "ZAR",
        "uic":         2073,
        "yf_ticker":   "EURZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPCNH",
        "description": "British Pound / Offshore Chinese Renminbi",
        "base":        "GBP",
        "quote":       "CNH",
        "uic":         52832,
        "yf_ticker":   "GBPCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPCZK",
        "description": "British Pound / Czech Koruna",
        "base":        "GBP",
        "quote":       "CZK",
        "uic":         9447,
        "yf_ticker":   "GBPCZK=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPHKD",
        "description": "British Pound / Hong Kong Dollar",
        "base":        "GBP",
        "quote":       "HKD",
        "uic":         5395,
        "yf_ticker":   "GBPHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPHUF",
        "description": "British Pound / Hungarian Forint",
        "base":        "GBP",
        "quote":       "HUF",
        "uic":         7609,
        "yf_ticker":   "GBPHUF=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPILS",
        "description": "British Pound / Israeli Shekel",
        "base":        "GBP",
        "quote":       "ILS",
        "uic":         26766,
        "yf_ticker":   "GBPILS=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPMXN",
        "description": "British Pound / Mexican Peso",
        "base":        "GBP",
        "quote":       "MXN",
        "uic":         14009,
        "yf_ticker":   "GBPMXN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPPLN",
        "description": "British Pound / Polish Zloty",
        "base":        "GBP",
        "quote":       "PLN",
        "uic":         8712,
        "yf_ticker":   "GBPPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPSGD",
        "description": "British Pound / Singapore Dollar",
        "base":        "GBP",
        "quote":       "SGD",
        "uic":         30,
        "yf_ticker":   "GBPSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPTRY",
        "description": "British Pound / Turkish Lira",
        "base":        "GBP",
        "quote":       "TRY",
        "uic":         23522,
        "yf_ticker":   "GBPTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "GBPZAR",
        "description": "British Pound / South African Rand",
        "base":        "GBP",
        "quote":       "ZAR",
        "uic":         5125,
        "yf_ticker":   "GBPZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "HKDJPY",
        "description": "Hong Kong Dollar / Japanese Yen",
        "base":        "HKD",
        "quote":       "JPY",
        "uic":         8943,
        "yf_ticker":   "HKDJPY=X",
        "pip_size":    0.001,
        "min_units":   50_000,
    },
    {
        "symbol":      "HUFJPY",
        "description": "Hungarian Forint / Japanese Yen",
        "base":        "HUF",
        "quote":       "JPY",
        "uic":         37129,
        "yf_ticker":   "HUFJPY=X",
        "pip_size":    0.001,
        "min_units":   100_000,
    },
    {
        "symbol":      "JPYHKD",
        "description": "Japanese Yen / Hong Kong Dollar",
        "base":        "JPY",
        "quote":       "HKD",
        "uic":         40321,
        "yf_ticker":   "JPYHKD=X",
        "pip_size":    1e-05,
        "min_units":   100_000,
    },
    {
        "symbol":      "MXNJPY",
        "description": "Mexican Peso / Japanese Yen",
        "base":        "MXN",
        "quote":       "JPY",
        "uic":         23581,
        "yf_ticker":   "MXNJPY=X",
        "pip_size":    0.001,
        "min_units":   10_000,
    },
    {
        "symbol":      "NZDCNH",
        "description": "New Zealand Dollar / Offshore Chinese Renminbi",
        "base":        "NZD",
        "quote":       "CNH",
        "uic":         52870,
        "yf_ticker":   "NZDCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDCZK",
        "description": "New Zealand Dollar / Czech Koruna",
        "base":        "NZD",
        "quote":       "CZK",
        "uic":         9449,
        "yf_ticker":   "NZDCZK=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDHKD",
        "description": "New Zealand Dollar / Hong Kong Dollar",
        "base":        "NZD",
        "quote":       "HKD",
        "uic":         40334,
        "yf_ticker":   "NZDHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDHUF",
        "description": "New Zealand Dollar / Hungarian Forint",
        "base":        "NZD",
        "quote":       "HUF",
        "uic":         9450,
        "yf_ticker":   "NZDHUF=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDMXN",
        "description": "New Zealand Dollar / Mexican Peso",
        "base":        "NZD",
        "quote":       "MXN",
        "uic":         30553,
        "yf_ticker":   "NZDMXN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDPLN",
        "description": "New Zealand Dollar / Polish Zloty",
        "base":        "NZD",
        "quote":       "PLN",
        "uic":         9451,
        "yf_ticker":   "NZDPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDSGD",
        "description": "New Zealand Dollar / Singapore Dollar",
        "base":        "NZD",
        "quote":       "SGD",
        "uic":         8183,
        "yf_ticker":   "NZDSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDTRY",
        "description": "New Zealand Dollar / Turkish Lira",
        "base":        "NZD",
        "quote":       "TRY",
        "uic":         23524,
        "yf_ticker":   "NZDTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "NZDZAR",
        "description": "New Zealand Dollar / South African Rand",
        "base":        "NZD",
        "quote":       "ZAR",
        "uic":         23525,
        "yf_ticker":   "NZDZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "PLNHUF",
        "description": "Polish Zloty / Hungarian Forint",
        "base":        "PLN",
        "quote":       "HUF",
        "uic":         36770,
        "yf_ticker":   "PLNHUF=X",
        "pip_size":    0.1,
        "min_units":   50_000,
    },
    {
        "symbol":      "PLNJPY",
        "description": "Polish Zloty / Japanese Yen",
        "base":        "PLN",
        "quote":       "JPY",
        "uic":         3901,
        "yf_ticker":   "PLNJPY=X",
        "pip_size":    0.01,
        "min_units":   50_000,
    },
    {
        "symbol":      "SGDCNH",
        "description": "Singapore Dollar / Offshore Chinese Renminbi",
        "base":        "SGD",
        "quote":       "CNH",
        "uic":         9095522,
        "yf_ticker":   "SGDCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "SGDHKD",
        "description": "Singapore Dollar / Hong Kong Dollar",
        "base":        "SGD",
        "quote":       "HKD",
        "uic":         23742,
        "yf_ticker":   "SGDHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "SGDJPY",
        "description": "Singapore Dollar / Japanese Yen",
        "base":        "SGD",
        "quote":       "JPY",
        "uic":         48,
        "yf_ticker":   "SGDJPY=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "TRYJPY",
        "description": "Turkish Lira / Japanese Yen",
        "base":        "TRY",
        "quote":       "JPY",
        "uic":         23582,
        "yf_ticker":   "TRYJPY=X",
        "pip_size":    0.1,
        "min_units":   5_000,
    },
    {
        "symbol":      "TRYZAR",
        "description": "Turkish Lira / South African Rand",
        "base":        "TRY",
        "quote":       "ZAR",
        "uic":         37130,
        "yf_ticker":   "TRYZAR=X",
        "pip_size":    0.001,
        "min_units":   5_000,
    },
    {
        "symbol":      "USDAED",
        "description": "US Dollar / UAE Dirham",
        "base":        "USD",
        "quote":       "AED",
        "uic":         1363,
        "yf_ticker":   "USDAED=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDCNH",
        "description": "US Dollar / Offshore Chinese Renminbi",
        "base":        "USD",
        "quote":       "CNH",
        "uic":         52872,
        "yf_ticker":   "USDCNH=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDCZK",
        "description": "US Dollar / Czech Koruna",
        "base":        "USD",
        "quote":       "CZK",
        "uic":         40,
        "yf_ticker":   "USDCZK=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDHKD",
        "description": "US Dollar / Hong Kong dollar",
        "base":        "USD",
        "quote":       "HKD",
        "uic":         1345,
        "yf_ticker":   "USDHKD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDHUF",
        "description": "US Dollar / Hungarian Forint",
        "base":        "USD",
        "quote":       "HUF",
        "uic":         2075,
        "yf_ticker":   "USDHUF=X",
        "pip_size":    0.1,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDILS",
        "description": "US Dollar / Israeli Shekel",
        "base":        "USD",
        "quote":       "ILS",
        "uic":         4773,
        "yf_ticker":   "USDILS=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDPLN",
        "description": "US Dollar / Polish Zloty",
        "base":        "USD",
        "quote":       "PLN",
        "uic":         47,
        "yf_ticker":   "USDPLN=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDRON",
        "description": "US Dollar / Romanian Leu",
        "base":        "USD",
        "quote":       "RON",
        "uic":         24407,
        "yf_ticker":   "USDRON=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDSGD",
        "description": "US Dollar / Singapore Dollar",
        "base":        "USD",
        "quote":       "SGD",
        "uic":         45,
        "yf_ticker":   "USDSGD=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDTHB",
        "description": "US Dollar / Thai Baht",
        "base":        "USD",
        "quote":       "THB",
        "uic":         1351,
        "yf_ticker":   "USDTHB=X",
        "pip_size":    0.01,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDTRY",
        "description": "US Dollar / Turkish Lira",
        "base":        "USD",
        "quote":       "TRY",
        "uic":         13928,
        "yf_ticker":   "USDTRY=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "USDZAR",
        "description": "US Dollar / South African Rand",
        "base":        "USD",
        "quote":       "ZAR",
        "uic":         1296,
        "yf_ticker":   "USDZAR=X",
        "pip_size":    0.001,
        "min_units":   1_000,
    },
    {
        "symbol":      "ZARJPY",
        "description": "South African Rand / Japanese Yen",
        "base":        "ZAR",
        "quote":       "JPY",
        "uic":         21281,
        "yf_ticker":   "ZARJPY=X",
        "pip_size":    0.1,
        "min_units":   15_000,
    },
    # ── Scandinavian cross pairs: Tier 3 "SCANDI" (added 2026-08-25) ─────────
    # Sourced from Saxo's own SaxoTraderGO screener, "Last three month's
    # popularity" sort, FX filter (188 total instruments) — the user
    # screenshotted the full scrollable list and every pair below is one
    # that appeared there but was missing from our then-117-pair universe.
    # All 32 are NOK/SEK/DKK crosses (our existing coverage only had these
    # three currencies paired against EUR/USD — EURNOK/EURSEK/USDNOK/
    # USDSEK/USDDKK above). UICs, Format.Decimals (-> pip_size), and
    # MinimumTradeSize all pulled live via find_instrument()/
    # /ref/v1/instruments/details on Saxo SIM, same as every other exotic
    # pair here — never guessed. SIM-only, for strategy testing; excluded
    # from LIVE by construction since LIVE hard-filters to CORE_SYMBOLS.
    {"symbol": "NOKSEK", "description": "Norwegian Krone / Swedish Krone", "base": "NOK", "quote": "SEK", "uic": 32,    "yf_ticker": "NOKSEK=X", "pip_size": 0.001,  "min_units": 10_000},
    {"symbol": "GBPNOK", "description": "British Pound / Norwegian Krone", "base": "GBP", "quote": "NOK", "uic": 27,    "yf_ticker": "GBPNOK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "GBPDKK", "description": "British Pound / Danish Krone",    "base": "GBP", "quote": "DKK", "uic": 25,    "yf_ticker": "GBPDKK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "CHFSEK", "description": "Swiss Franc / Swedish Krone",     "base": "CHF", "quote": "SEK", "uic": 1305,  "yf_ticker": "CHFSEK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "AUDNOK", "description": "Australian Dollar / Norwegian Krone", "base": "AUD", "quote": "NOK", "uic": 30630, "yf_ticker": "AUDNOK=X", "pip_size": 0.001, "min_units": 1_000},
    {"symbol": "SEKJPY", "description": "Swedish Krone / Japanese Yen",    "base": "SEK", "quote": "JPY", "uic": 2870,  "yf_ticker": "SEKJPY=X", "pip_size": 0.01,   "min_units": 50_000},
    {"symbol": "GBPSEK", "description": "British Pound / Swedish Krone",   "base": "GBP", "quote": "SEK", "uic": 29,    "yf_ticker": "GBPSEK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "SEKDKK", "description": "Swedish Krone / Danish Krone",    "base": "SEK", "quote": "DKK", "uic": 2047,  "yf_ticker": "SEKDKK=X", "pip_size": 0.001,  "min_units": 50_000},
    {"symbol": "CADNOK", "description": "Canadian Dollar / Norwegian Krone", "base": "CAD", "quote": "NOK", "uic": 6158, "yf_ticker": "CADNOK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "NOKDKK", "description": "Norwegian Krone / Danish Krone",  "base": "NOK", "quote": "DKK", "uic": 2046,  "yf_ticker": "NOKDKK=X", "pip_size": 0.001,  "min_units": 10_000},
    {"symbol": "SEKNOK", "description": "Swedish Krone / Norwegian Krone", "base": "SEK", "quote": "NOK", "uic": 2048,  "yf_ticker": "SEKNOK=X", "pip_size": 0.001,  "min_units": 50_000},
    {"symbol": "JPYDKK", "description": "Japanese Yen / Danish Krone",     "base": "JPY", "quote": "DKK", "uic": 2115,  "yf_ticker": "JPYDKK=X", "pip_size": 0.0001, "min_units": 100_000},
    {"symbol": "NZDSEK", "description": "New Zealand Dollar / Swedish Krone", "base": "NZD", "quote": "SEK", "uic": 9452, "yf_ticker": "NZDSEK=X", "pip_size": 0.001, "min_units": 1_000},
    {"symbol": "CADSEK", "description": "Canadian Dollar / Swedish Krone",  "base": "CAD", "quote": "SEK", "uic": 36897, "yf_ticker": "CADSEK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "NZDNOK", "description": "New Zealand Dollar / Norwegian Krone", "base": "NZD", "quote": "NOK", "uic": 5396, "yf_ticker": "NZDNOK=X", "pip_size": 0.001, "min_units": 1_000},
    {"symbol": "TRYDKK", "description": "Turkish Lira / Danish Krone",     "base": "TRY", "quote": "DKK", "uic": 21321, "yf_ticker": "TRYDKK=X", "pip_size": 0.001,  "min_units": 5_000},
    {"symbol": "CHFDKK", "description": "Swiss Franc / Danish Krone",      "base": "CHF", "quote": "DKK", "uic": 1311,  "yf_ticker": "CHFDKK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "AUDSEK", "description": "Australian Dollar / Swedish Krone", "base": "AUD", "quote": "SEK", "uic": 24392, "yf_ticker": "AUDSEK=X", "pip_size": 0.001, "min_units": 1_000},
    {"symbol": "DKKZAR", "description": "Danish Krone / South African Rand", "base": "DKK", "quote": "ZAR", "uic": 9445, "yf_ticker": "DKKZAR=X", "pip_size": 0.001, "min_units": 1_000},
    {"symbol": "EURDKK", "description": "Euro / Danish Krone",             "base": "EUR", "quote": "DKK", "uic": 16,    "yf_ticker": "EURDKK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "SEKPLN", "description": "Swedish Krone / Polish Zloty",    "base": "SEK", "quote": "PLN", "uic": 21295, "yf_ticker": "SEKPLN=X", "pip_size": 0.001,  "min_units": 50_000},
    {"symbol": "NZDDKK", "description": "New Zealand Dollar / Danish Krone", "base": "NZD", "quote": "DKK", "uic": 3864, "yf_ticker": "NZDDKK=X", "pip_size": 0.001, "min_units": 1_000},
    {"symbol": "DKKJPY", "description": "Danish Krone / Japanese Yen",     "base": "DKK", "quote": "JPY", "uic": 4727,  "yf_ticker": "DKKJPY=X", "pip_size": 0.01,   "min_units": 1_000},
    {"symbol": "NOKCZK", "description": "Norwegian Krone / Czech Koruna",  "base": "NOK", "quote": "CZK", "uic": 41943, "yf_ticker": "NOKCZK=X", "pip_size": 0.01,   "min_units": 10_000},
    {"symbol": "PLNDKK", "description": "Polish Zloty / Danish Krone",     "base": "PLN", "quote": "DKK", "uic": 3934,  "yf_ticker": "PLNDKK=X", "pip_size": 0.001,  "min_units": 50_000},
    {"symbol": "AUDDKK", "description": "Australian Dollar / Danish Krone", "base": "AUD", "quote": "DKK", "uic": 3863, "yf_ticker": "AUDDKK=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "DKKHUF", "description": "Danish Krone / Hungarian Forint", "base": "DKK", "quote": "HUF", "uic": 9442,  "yf_ticker": "DKKHUF=X", "pip_size": 0.1,    "min_units": 1_000},
    {"symbol": "DKKCZK", "description": "Danish Krone / Czech Koruna",     "base": "DKK", "quote": "CZK", "uic": 9441,  "yf_ticker": "DKKCZK=X", "pip_size": 0.01,   "min_units": 1_000},
    {"symbol": "PLNSEK", "description": "Polish Zloty / Swedish Krone",    "base": "PLN", "quote": "SEK", "uic": 20300, "yf_ticker": "PLNSEK=X", "pip_size": 0.001,  "min_units": 50_000},
    {"symbol": "DKKSGD", "description": "Danish Krone / Singapore Dollar", "base": "DKK", "quote": "SGD", "uic": 9443,  "yf_ticker": "DKKSGD=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "DKKPLN", "description": "Danish Krone / Polish Zloty",     "base": "DKK", "quote": "PLN", "uic": 21294, "yf_ticker": "DKKPLN=X", "pip_size": 0.001,  "min_units": 1_000},
    {"symbol": "SGDSEK", "description": "Singapore Dollar / Swedish Krone", "base": "SGD", "quote": "SEK", "uic": 40953, "yf_ticker": "SGDSEK=X", "pip_size": 0.001, "min_units": 1_000},
]

ASSET_TYPE = "FxSpot"

# ── Universe tiers ──────────────────────────────────────────────────────────
# CORE = the original 34 majors/crosses/Scandi — the live-trading-candidate
# universe once the account goes live. EXOTIC = the 83 EM/exotic pairs added
# 2026-08-21 for SIM-only broad testing. SCANDI = 32 more NOK/SEK/DKK cross
# pairs added 2026-08-25 (see the "Tier 3" comment above PAIRS) — Saxo's own
# popularity ranking showed these as actively traded, but our CORE/EXOTIC
# coverage only ever paired NOK/SEK/DKK against EUR/USD. All three tiers are
# scanned together by every strategy (see SLOTS_PER_STRATEGY in
# forex/runner.py) so nothing is missed, but every trade is tagged by tier so
# P&L/win-rate can be evaluated separately per tier — that's how the
# live-universe decision gets made: review EXOTIC's (and now SCANDI's) SIM
# track record, then decide whether to fold any of it into CORE for live
# trading. LBO always trades its own narrower 28-pair subset of CORE
# regardless of this tiering.
CORE_SYMBOLS = {
    "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "NZDUSD", "USDCHF",
    "EURGBP", "EURJPY", "GBPJPY", "AUDJPY", "CADJPY",
    "EURAUD", "EURNZD", "EURCAD", "EURCHF",
    "GBPAUD", "GBPCAD", "GBPCHF", "GBPNZD",
    "AUDCAD", "AUDCHF", "AUDNZD",
    "NZDJPY", "NZDCAD", "NZDCHF",
    "CHFJPY", "CADCHF",
    "EURNOK", "EURSEK", "USDNOK", "USDSEK", "USDDKK", "USDMXN",
}

SCANDI_SYMBOLS = {
    "NOKSEK", "GBPNOK", "GBPDKK", "CHFSEK", "AUDNOK", "SEKJPY", "GBPSEK", "SEKDKK",
    "CADNOK", "NOKDKK", "SEKNOK", "JPYDKK", "NZDSEK", "CADSEK", "NZDNOK", "TRYDKK",
    "CHFDKK", "AUDSEK", "DKKZAR", "EURDKK", "SEKPLN", "NZDDKK", "DKKJPY", "NOKCZK",
    "PLNDKK", "AUDDKK", "DKKHUF", "DKKCZK", "PLNSEK", "DKKSGD", "DKKPLN", "SGDSEK",
}


def get_tier(symbol: str) -> str:
    """'core' (live-trading candidate, 34 pairs), 'scandi' (SIM-only NOK/SEK/DKK
    crosses, 32 pairs), or 'exotic' (SIM-only, everything else, 83 pairs)."""
    if symbol in CORE_SYMBOLS:
        return "core"
    if symbol in SCANDI_SYMBOLS:
        return "scandi"
    return "exotic"


# Lookup helpers
_BY_SYMBOL = {p["symbol"]: p for p in PAIRS}
_BY_UIC    = {p["uic"]:    p for p in PAIRS}


def get_pair(symbol: str) -> dict:
    return _BY_SYMBOL[symbol]


def get_all() -> list:
    return list(PAIRS)


def price_decimals(symbol: str) -> int:
    """The instrument's own price decimal precision, derived from its
    pip_size (which was itself pulled live from Saxo's Format.Decimals when
    this universe was built — see the module docstring). Inverse of
    pip_size = 10 ** -(decimals - 1).

    Added 2026-08-21 — saxo_order.py used to guess FxSpot decimal places
    generically (5dp, or 3dp for JPY crosses only), which is wrong for any
    other pair that isn't 5dp: found via a live PriceNotInTickSizeIncrements
    rejection on AUDTRY's stop order (pip_size 0.001 = 4dp, not 5dp). Any
    TRY- or CNH-quoted pair hits the same wrong-precision bug. Pass this
    to saxo_order.place_with_stop(price_decimals=...) instead of letting it
    guess from the symbol string.
    """
    pip = _BY_SYMBOL[symbol]["pip_size"]
    d = 0
    v = pip
    while v < 0.999999 and d < 10:
        v *= 10
        d += 1
    return d + 1
